### ISSUE TITLE
UI bugs 

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#10]
- [x] #18
- [x] 3.	Область справа начнает двигаться при вводе Name.
- [x]  4.	Поле Media
           - Плейсхолдер не выровнен относительно других плейсхолдеров и находиться правее
           - По первому нажатию на всю зону импута предлагать выбор медиа 
           - Сам инпут слишком маленький и картинку в нем не видно — сделать шире  
           - Отступ от картинки до текста должен быть равен стандартному отступу 
- [x] #21
- [x] 6.	Автозаполнение Payout Address.
- [x] #20
- [x] 8.	В поле description отличается Паддинг сверху от остальных инпутов.
- [x] #19

**Comment by AllDayAlone** [comment]
Пофиксил 
6. Автозаполнение Payout Address.
10. Кнопка Connect Wallet пропадает

**Comment by anstill** [comment]
11. Названия кошельков вылезают за пределы по нажатию Connect wallet

**Comment by kazeens** [comment]
5. Дизайн датапикера в соотвествии с указанми стилями достаточно времязатратное дело.
Предлагаю оставить текущий пикер, только подправить цвета в соответсвии с нашим приложением
2. Symbol - сделаю до вторника
3. Payout адрес обновленный дизайн - сделаю до вторника

По остальным вопросам жду плотного содействия от @BooleanPanda

**Comment by kazeens** [comment]
@BooleanPanda можешь глянуть пожалуйста остальные задачи и взять по возможности все что можешь
Возможно где-то нужна будет моя помощь

**Comment by kazeens** [comment]
Буду рад помочь

**Comment by kazeens** [comment]
На issues-ы 10-14 нужно погружатся на день-два.
Библиотека сама по себе содержит много багов. Собственно в ее read.me об этом говорится (work in progress, могут быть баги).

По моим оценкам нужно самостоятельно реализовывать эту кнопку используя ton connect sdk.
На это нужно время. 
Вижу для смысл пока чуть отложить эту задачу, возможно кто-то другой еще глянет как можно решить эти проблемы  меньшим трудом

**Comment by anstill** [comment]
@kazeens посмотри сюда https://github.com/delab-team/connect
