### ISSUE TITLE
Fix unknown message on Free editions

### ISSUE THREAD

**Issue by AllDayAlone** [theoberton/3.14xl#106]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/32430949/225738569-20f58bc5-924b-4205-92d5-205fed587734.png">

**Comment by anstill** [comment]
Transaction to Pixel wallet. We shouldn’t send it.

![BF4273E9-BA42-4DC1-B3B5-5E90E40184A6](https://user-images.githubusercontent.com/16906128/225931252-53eafff0-fc72-4af3-9c03-9de8ed7519cd.png)
