### ISSUE TITLE
Can't recive PIxel mint fee on our wallet 

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#112]
https://dton.io/tx/70A7FCBCB7F7F21D3CD0AC6E45BB47BFECD0D5A736EBBBD210A9F7BFD70A9A5F?time=2023-03-17T15:13:38
<img width="1332" alt="Screenshot 2023-03-17 at 15 25 49" src="https://user-images.githubusercontent.com/16906128/225904137-368a83da-7e91-47d4-a93d-e29180cd5500.png">

**Comment by AllDayAlone** [comment]
Fixed after wallet activation
