### ISSUE TITLE
Can't open edition after creation

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#23]
Collection [link](https://pi.oberton.io/#/edition/EQBdqF8jIJn9sjschMq8zgGGgiWhri4OtwmcvN-aBvBVtm_R) [link2](https://pi.oberton.io/#/edition/EQDIvn-k-paeMDIP6zOKusYbdw_pO_1Jadwr3gAX0MIguX6O)

**_Testnet should be enabled._** 

Result: 
<img width="1742" alt="Screenshot 2023-03-03 at 17 35 32" src="https://user-images.githubusercontent.com/16906128/222748441-baf2762b-1833-427f-a968-cb9e2a603068.png">

Data: 
<img width="655" alt="Screenshot 2023-03-03 at 17 41 49" src="https://user-images.githubusercontent.com/16906128/222749592-989b56fe-4ffd-46ec-80d5-9c898389247d.png">

It was possible to get to the page right after creation by clicking on the button, but after the refresh, it doesn't work anymore.

**Comment by kazeens** [comment]
Temporary fixed with console log
