### ISSUE TITLE
Make TonConnect great again

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#24]
- [x] Кнопка Connect Wallet пропадает
- [x] Кошельки (кроме tonkeeper-а) и их подключение не одинаково предсказуемо работает
- [x] Проверить работу других кошельков 
- [x] Названия кошельков вылезают за пределы по нажатию Connect wallet
- [x] #16
- [x] #44
- [ ] #71

Delabs Connect can be used https://github.com/delab-team/connect

**Comment by kazeens** [comment]
@AllDayAlone 
Вот пример нормального dapp с нормально работающим функционалом
https://github.com/ton-connect/demo-dapp (ton-connect 2)
