### ISSUE TITLE
Edition symbol must be one word

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#25]
Auto-generated symbol maximum length is 4 characters, but with no limit characters for user input. 

<img width="637" alt="Screenshot 2023-03-03 at 17 59 33" src="https://user-images.githubusercontent.com/16906128/222753300-a252f118-d07a-4bee-87ee-fd763ec21669.png">

**Comment by kazeens** [comment]
@anstill 
Т.е если в Name вводится
Teseract

В Symbol должно загенирировать $TESE?

Но если юзер сам вводит текст а поле Symbol то там может быть неограниченная длина символов, но без пробела

Ты это имеешь ввиду?

**Comment by anstill** [comment]
Take the first 4 consonants. Teseract -> Tsrc 

> Но если юзер сам вводит текст а поле Symbol то там может быть неограниченная длина символов, но без пробела

Да, неограниченно или дэфолтное колличество символов которое мы используем в инпутах или другое разумное ограничение ( Например, не больше 10 символов)
