### ISSUE TITLE
Show validation errors for requred fields

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#30]
The button is disabled, but no errors. 

Fields mission on the screenshot: Description and Amount (Particularly obscure due to the placeholder).

<img width="674" alt="Screenshot 2023-03-03 at 18 17 29" src="https://user-images.githubusercontent.com/16906128/222757413-decadb19-a583-4174-8484-34c78b11f2d8.png">

**Comment by kazeens** [comment]
Нужно очень постараться чтобы целенаправлено заполнять форму, дойти до ройалти, как-то пропустить ЦЕНУ и описание и думать почему же оно не работает.
Очень странный use case

Если проблема в том что плейсхолдеры как бы заставляют юзера думать что поле уже заполнено то оочень непонятно чья это проблема.
На мой взгляд все ок и плейсходлер тоже ок, валидация работает корректно когда ты прикоснешься к любому из этих полей(isDirty).

description сделан кстати optional, и кнопочка субмита загорится как только будет введена цена

Ничего пока не меняю по этой задаче

сс @anstill

**Comment by anstill** [comment]
Достаточно сделать кнопку Create Edition активной, и по нажатию подсветить незаполненые поля.  

Description is optional, ok.

**Comment by kazeens** [comment]
Сделаю непременно
