### ISSUE TITLE
Check if the styles of the application match the current design

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#32]

**Comment by kazeens** [comment]
О чем конкретно в этой задаче идет речь?

Пиксель перфект верстку я думаю мы не собираемся делать(есть ли в этом смысл?). 
Тем более ресурс всего достаточно ограничен и занят, чтобы приоритезировать эту задачу.
Нужна кокректика 

сс @anstill

**Comment by AllDayAlone** [comment]
Landing page
- кубики слишком маленькие и отвлекают движением. Предложение вернуть крупные версии и добавить анимацию (увелиение или поворот (или свечение)) при взаимоделствии мышкой/скролом/ховером
-градиент meh, больше нравилось белым
- bring сделать цельным, отцентрировать вертиклаьно
- explore mroe primary не важно
- странно что именно 3 колекции на главной, хотя бы6 или 9
- дизайн футера

Tonkeeper connect
-приклееные расстояния
- сделать разные цвета для AddressLabel
- расстояния до мейн контента

Переход на my editions крашится

Create ediion:
- цвет кратинки
- лесенка на картинке
- скругление углов
- расстояние до контента
- выравнивание внутри штучек на превьё
- календари


Preview
- share убрать
- картинка на одну ширину

проверить все роутинги

**Comment by anstill** [comment]
- [ ] Remove `Create new edition button`

<img width="594" alt="Screenshot 2023-03-12 at 20 00 05" src="https://user-images.githubusercontent.com/16906128/224560116-f5e3e55e-7e10-4b3f-9f7d-bdadedb0907b.png">
