### ISSUE TITLE
Add ability to create and mint tokens through telegram bot 

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#39]
Telegram bot architecture: 

1. Must support TWA (telegram web application)
2. Should be deployed on vercel and use serverless function (DM @anstill for vercel credentials) 

https://github.com/m7mark/telegram-bot-vercel-boilerplate

Functionality: 

1. Should save Links to created collections in the chat. 
2. Should support opening links to the collection in the bot

Flow: 
1. Open Bot 
2. Show Description and Let the User Know [how to start the Bot](https://telegra.ph/pkav-12-29)
4. Start Bot 
5. Show Button/Menu to open [Pixel](https://pi.oberton.io/) inside TWA 
6. Open Pixel  inside TWA 
7. Normal creation flow: Create Edition -> Fill fields -> Create -> Redirect Edition Page
8. Bot Should sent link to created Edition to the chat after creation 

Also, User should be able to Mint Edition through the bot. 

Future Implementation: 

- [ ] #42

**Comment by kazeens** [comment]
Ready but needs wallet task to be completed in order to work properly

**Comment by anstill** [comment]
@kazeens Do you need separate repo for this?

**Comment by anstill** [comment]
Create `314xl-backend` repo for bots and pixel backend

**Comment by kazeens** [comment]
Close the issue
Cause primary task is done
It is going to work once wallet part is completed
