### ISSUE TITLE
Add link preview

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#40]
Examples: 

<img width="482" alt="Screenshot 2023-03-03 at 22 58 14" src="https://user-images.githubusercontent.com/16906128/222814967-6e909dae-103d-4264-9aa4-d90fcca4794e.png">
<img width="423" alt="Screenshot 2023-03-03 at 22 58 28" src="https://user-images.githubusercontent.com/16906128/222814974-de93c5e0-7585-43a0-b086-787b1e738223.png">
<img width="469" alt="Screenshot 2023-03-03 at 22 58 50" src="https://user-images.githubusercontent.com/16906128/222814978-eb1b147c-5bc7-4519-9a9c-ff9ecf74b6d5.png">

**Comment by kazeens** [comment]
Нужно согласовать скрин на main-page с дизайнером
cc @anstill
