### ISSUE TITLE
Pixel Fee

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#51]
- [x] Inform the creator that we take 5% of primary sales. Add text under `Create Edition` button.  Text: "5% of primary sales goes to 3.14XL"
- [x] Set Fee wallet to `EQAkL7VQ5_K7Ksc_J2xnAM_umLjed1aPekxOk0drbQcnGfWy`. This is a brand-new empty wallet. Later it will be changed to a DAO wallet.

**Comment by AllDayAlone** [comment]
Waiting for pubkey of this wallet to empower tests
