### ISSUE TITLE
Add Share Buttons 

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#54]
Add share buttons after the creation of the Edition.  

Share to Twitter and Telegram. 

The shared item should contain some profiled text, see the example below.

Examples, the text should be changed to ours:
<img width="783" alt="Screenshot 2023-03-06 at 15 54 46" src="https://user-images.githubusercontent.com/16906128/223116092-687f9823-54b4-4fe3-83cb-583867d9907e.png">
<img width="645" alt="Screenshot 2023-03-06 at 15 56 30" src="https://user-images.githubusercontent.com/16906128/223116498-63c5b1a7-20ee-4135-8434-9e9373689381.png">

**Comment by kazeens** [comment]
Return to the task on Saturday

**Comment by anstill** [comment]
Share buttons already presented on modal after creation edition.
