### ISSUE TITLE
Idea: Send TON/Jetton/NFT or any other assets to person who don’t have wallet

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#57]
We can easily implement it in TON even without servers. 

Sender — User who wants to send some access.
Receiver — User who doesn't have yet TON wallet 
Asset — TON/NFT/Jetton

Flow: 
1. Sender goes to the page where they can connect wallet and attach some assets
2. Sender selects assets that want to transfer and approve transactions in the wallet 
3. System generates a link that should be sent to Receiver
4. Receiver opens the link and has the ability to Claim assets that were transferred. To claim access they should download TON wallet and provide an address where assets should be sent. Step-by-step instructions on how to install the wallet are provided on the page.

Architecture:
1. Generate a new wallet with a new mnemonic for every Sender transaction. 
2. Send assets to this wallet from Sender's wallet 
3*. Include this info (mnemonic or private key) in the link which sends to Receiver
4. Use the info from the link to access the temp wallet and transfer assets to the permanent User wallet which should be created while this process. 

3* If link will be to long and ugly we can provide some Hash or ID and store this info in our database

**Comment by AllDayAlone** [comment]
https://github.com/theoberton/locker
