### ISSUE TITLE
Invalid Price

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#59]
- [x] The user should be able to submit any **positive** pieces including fractionals up to 9 decimals. 
- [ ] Change zero price to the free label on the mint page

<img width="663" alt="Screenshot 2023-03-07 at 15 32 06" src="https://user-images.githubusercontent.com/16906128/223424504-f7f22977-615d-49c5-bddd-d4be6467f3d2.png">
<img width="702" alt="Screenshot 2023-03-07 at 15 39 33" src="https://user-images.githubusercontent.com/16906128/223424582-2b117d51-032e-4a1e-aea1-d4aa41f4906d.png">

**Comment by kazeens** [comment]
Check that on mobile phones it is offered number keyboard
