### ISSUE TITLE
Preview for new collections doesn't work on main page

### ISSUE THREAD

**Issue by anstill** [theoberton/3.14xl#76]
Preview and titel not shown for latest collection 

<img width="1744" alt="Screenshot 2023-03-12 at 13 23 42" src="https://user-images.githubusercontent.com/16906128/224538574-fffcc877-6513-4716-92ee-76d4a1e4dd94.png">

**Comment by AllDayAlone** [comment]
Same for me. It's fine on the details page BTW
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/32430949/224539963-b8c85905-3cae-43e3-8dca-e9157a95085b.png">

**Comment by kazeens** [comment]
@anstill @AllDayAlone это коллекция по всей видимости создалась с ошибкой в базе (вопрос почему)
Я убрал этот и другие документы с неверной структурой.

Снова такую проблему я не смогу воспроизвести (testnent, mainnet)
Пока закрываю задачу
Если кто-то воспроизведет снова - пишите посмотрю глубже
